# Generated by Django 4.2.27 on 2026-01-24 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('visit_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='visitors/qrcodes/')),
                ('badge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_checkin', models.DateTimeField(blank=True, null=True)),
                ('actual_checkout', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='organizations.organization')),
                ('visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.visittype')),
                ('whom_to_meet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('whom_to_meet_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_employee', to='dashboard.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='visitors.visitrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['organization', 'visit_date'], name='visitors_vi_organiz_00e0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['organization', 'status'], name='visitors_vi_organiz_49cc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code'], name='visitors_ot_code_3ee97a_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='visitors_ot_expires_229c71_idx'),
        ),
    ]
