# Generated by Django 4.2.27 on 2026-01-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full company name (e.g., Demo Company Pvt Ltd)', max_length=255)),
                ('code', models.SlugField(help_text='Short unique code used internally (e.g., demo, abc)', unique=True)),
                ('domain', models.CharField(help_text='Full domain mapped to this organization (e.g., demo-vistron.zaryz.com)', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Disable organization access without deleting data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(blank=True, help_text='Optional override sender email', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Enable tenant SMTP')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_config', to='organizations.organization')),
            ],
        ),
    ]
